# Generated by Django 4.1.3 on 2023-01-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0003_orderhistory_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory_customer',
            name='customer_id',
            field=models.BigIntegerField(),
        ),
    ]
