# Generated by Django 4.1.3 on 2023-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0004_alter_orderhistory_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory_customer',
            name='product_name',
            field=models.TextField(default='dvf', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderhistory_customer',
            name='total',
            field=models.TextField(max_length=255),
        ),
    ]
