# Generated by Django 4.1.3 on 2023-01-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0008_orderhistory_customer_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory_customer',
            name='shop_id',
            field=models.BigIntegerField(),
        ),
    ]
