# Generated by Django 4.1.3 on 2023-01-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0010_orderhistory_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory_customer',
            name='delivered',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='orderhistory_customer',
            name='delivered_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
