# Generated by Django 4.1.3 on 2023-01-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_seller_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
