# Generated by Django 4.1.3 on 2023-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_seller_address_seller_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.TextField(default='fdfdfd', max_length=255),
        ),
    ]
