# Generated by Django 4.1.3 on 2023-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.TextField(max_length=255),
        ),
    ]
