# Generated by Django 4.1.3 on 2023-01-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('brand_name', models.TextField(max_length=255)),
                ('quantity', models.TextField(max_length=255)),
                ('price', models.TextField(max_length=255)),
                ('isAvailable', models.CharField(default='0', max_length=2)),
                ('seller_id', models.BigIntegerField(max_length=20)),
            ],
        ),
    ]
