# Generated by Django 4.1.3 on 2023-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('brand_name', models.TextField(max_length=255)),
                ('product_photo', models.TextField(max_length=255)),
                ('category', models.TextField(max_length=255)),
                ('quantity', models.TextField(max_length=255)),
                ('price', models.TextField(max_length=255)),
                ('shop_id', models.BigIntegerField()),
                ('shop_name', models.TextField(max_length=255)),
                ('generic_name', models.TextField(blank=True, max_length=255, null=True)),
                ('sub_category', models.TextField(max_length=255)),
                ('contradiction', models.TextField(blank=True, max_length=1500, null=True)),
                ('pharmacology', models.TextField(blank=True, max_length=1500, null=True)),
                ('interaction', models.TextField(blank=True, max_length=1500, null=True)),
                ('side_effects', models.TextField(blank=True, max_length=1500, null=True)),
                ('pregnancy', models.TextField(blank=True, max_length=1500, null=True)),
                ('warnings', models.TextField(blank=True, max_length=1500, null=True)),
                ('therapeutic', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
