# Generated by Django 4.1.3 on 2023-01-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller_product',
            new_name='Shop_product',
        ),
        migrations.RenameField(
            model_name='shop_product',
            old_name='seller_id',
            new_name='shop_id',
        ),
    ]
