# Generated by Django 4.1.3 on 2023-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_product',
            name='stock_Availability',
            field=models.TextField(default='Yes', max_length=55),
        ),
    ]
