# Generated by Django 4.1.3 on 2023-01-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_shop_product_stock_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_product',
            name='stock_Availability',
        ),
    ]
