# Generated by Django 4.1.3 on 2023-01-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_seller_product_shop_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_product',
            name='category',
            field=models.TextField(default='djfc', max_length=255),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='product_photo',
            field=models.TextField(default='ddfbd', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_product',
            name='shop_id',
            field=models.BigIntegerField(),
        ),
    ]
