# Generated by Django 4.1.3 on 2023-01-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_shop_product_category_shop_product_product_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_product',
            name='category',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_product',
            name='product_photo',
            field=models.TextField(max_length=255),
        ),
    ]
