# Generated by Django 4.1.3 on 2023-01-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_shop_product_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_product',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
