# Generated by Django 4.1.3 on 2023-01-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_shop_product_generic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shop_product',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='shop_product',
            name='isAvailable',
        ),
        migrations.AddField(
            model_name='shop_product',
            name='contradiction',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='interaction',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='pharmacology',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='pregnancy',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='side_effects',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='storage_condition',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='sub_category',
            field=models.TextField(default='dfbgfbbg', max_length=255),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='therapeutic',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='shop_product',
            name='warnings',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='shop_product',
            name='generic_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
