# Generated by Django 4.1.3 on 2023-01-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_alter_shop_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField()),
                ('cart_id', models.BigIntegerField()),
            ],
        ),
    ]
