# Generated by Django 4.1.3 on 2023-01-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_orderhistory_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_product',
            name='shop_name',
            field=models.TextField(default='Selina Pharmacy', max_length=255),
        ),
    ]
