# Generated by Django 4.1.3 on 2023-01-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_shop_product_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_product',
            name='shop_name',
            field=models.TextField(max_length=255),
        ),
    ]
