# Generated by Django 4.1.3 on 2023-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_open_dt_orderhistory_seller_delivered_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory_seller',
            name='verified',
            field=models.TextField(default='No', max_length=255),
        ),
    ]
