# Generated by Django 4.1.3 on 2023-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_orderhistory_seller_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory_seller',
            name='company_name',
            field=models.TextField(default='dddd', max_length=255),
        ),
    ]
