# Generated by Django 4.1.3 on 2023-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_orderhistory_seller_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory_seller',
            name='company_name',
            field=models.TextField(max_length=255),
        ),
    ]
