# Generated by Django 4.1.3 on 2023-01-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_id',
            field=models.BigIntegerField(),
        ),
    ]
