# Generated by Django 4.1.3 on 2023-01-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.CharField(default='Yes', max_length=3),
        ),
    ]
