# Generated by Django 4.1.3 on 2023-01-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
